# Generated by Django 4.2.3 on 2024-09-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FineTuneExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('system', models.TextField(blank=True, null=True)),
                ('assistant', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FineTunningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.CharField(max_length=255, unique=True)),
                ('output_model', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
